java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\btlaf_logoref_001_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\btlaf_logoref_002_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\btlaf_logoref_003_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\btlaf_logo_blur_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\btlaf_logo_glow_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\btlaf_logo_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\btl_trance_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\cmn_heada_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\cmn_hpmp_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\cmn_lay_main01_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\cmn_lv_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\cmn_new_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\cmn_next_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\cmn_page_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\gmov_logo_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\icon_status_02_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\icon_status_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\ic_itmeffect_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mgcg_hp_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mgml_rank_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mj_critical_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mj_defend_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mj_guard_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mj_miss_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mj_quick_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mj_reflection_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mj_shell_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mj_shield_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\mj_slow_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\rst_cateun_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\rst_lvup_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair   original-es\tai_plate_es.dds

