java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\btlaf_logoref_001_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\btlaf_logoref_002_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\btlaf_logoref_003_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\btlaf_logo_blur_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\btlaf_logo_glow_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\btlaf_logo_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\btl_trance_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\cmn_heada_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\cmn_hpmp_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\cmn_lay_main01_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\cmn_lv_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\cmn_new_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\cmn_next_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\cmn_page_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\gmov_logo_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\icon_status_02_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\icon_status_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\ic_itmeffect_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mgcg_hp_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mgml_rank_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mj_critical_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mj_defend_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mj_guard_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mj_miss_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mj_quick_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mj_reflection_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mj_shell_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mj_shield_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\mj_slow_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\rst_cateun_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\rst_lvup_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    original-us\tai_plate_us.dds

