java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logoref_001_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logoref_002_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logoref_003_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logo_blur_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logo_glow_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logo_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btl_trance_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_heada_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_hpmp_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_lay_main01_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_lv_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_new_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_next_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_page_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair gmov_logo_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair icon_status_02_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair icon_status_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair ic_itmeffect_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mgcg_hp_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mgml_rank_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_critical_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_defend_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_guard_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_miss_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_quick_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_reflection_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_shell_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_shield_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_slow_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair rst_cateun_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair rst_lvup_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair tai_plate_us.dds

