java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\btlaf_logoref_001_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\btlaf_logoref_002_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\btlaf_logoref_003_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\btlaf_logo_blur_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\btlaf_logo_glow_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\btlaf_logo_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\btl_trance_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\cmn_heada_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\cmn_hpmp_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\cmn_lay_main01_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\cmn_lv_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\cmn_new_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\cmn_next_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\cmn_page_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\gmov_logo_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\icon_status_02_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\icon_status_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\ic_itmeffect_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mgcg_hp_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mgml_rank_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mj_critical_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mj_defend_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mj_guard_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mj_miss_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mj_quick_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mj_reflection_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mj_shell_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mj_shield_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\mj_slow_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\rst_cateun_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\rst_lvup_us.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair    novas\tai_plate_us.dds

