java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logoref_001_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logoref_002_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logoref_003_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logo_blur_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logo_glow_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btlaf_logo_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair btl_trance_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_heada_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_hpmp_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_lay_main01_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_lv_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_new_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_next_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair cmn_page_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair gmov_logo_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair icon_status_02_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair icon_status_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair ic_itmeffect_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mgcg_hp_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mgml_rank_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_critical_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_defend_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_guard_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_miss_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_quick_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_reflection_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_shell_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_shield_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair mj_slow_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair rst_cateun_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair rst_lvup_es.dds
java -cp ..\tools\tool bluedragon.texturas.Extrair tai_plate_es.dds

