java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logoref_001_us.dds  _extraido_btlaf_logoref_001_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logoref_002_us.dds  _extraido_btlaf_logoref_002_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logoref_003_us.dds  _extraido_btlaf_logoref_003_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logo_blur_us.dds _extraido_btlaf_logo_blur_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logo_glow_us.dds _extraido_btlaf_logo_glow_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logo_us.dds _extraido_btlaf_logo_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btl_trance_us.dds _extraido_btl_trance_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_heada_us.dds _extraido_cmn_heada_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_hpmp_us.dds _extraido_cmn_hpmp_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_lay_main01_us.dds _extraido_cmn_lay_main01_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_lv_us.dds _extraido_cmn_lv_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_new_us.dds _extraido_cmn_new_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_next_us.dds _extraido_cmn_next_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_page_us.dds _extraido_cmn_page_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar gmov_logo_us.dds _extraido_gmov_logo_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar icon_status_02_us.dds _extraido_icon_status_02_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar icon_status_us.dds _extraido_icon_status_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar ic_itmeffect_us.dds _extraido_ic_itmeffect_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mgcg_hp_us.dds _extraido_mgcg_hp_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mgml_rank_us.dds _extraido_mgml_rank_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_critical_us.dds _extraido_mj_critical_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_defend_us.dds _extraido_mj_defend_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_guard_us.dds _extraido_mj_guard_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_miss_us.dds _extraido_mj_miss_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_quick_us.dds _extraido_mj_quick_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_reflection_us.dds _extraido_mj_reflection_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_shell_us.dds _extraido_mj_shell_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_shield_us.dds _extraido_mj_shield_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_slow_us.dds _extraido_mj_slow_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar rst_cateun_us.dds _extraido_rst_cateun_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar rst_lvup_us.dds _extraido_rst_lvup_us.dds
java -cp ..\tools\tool bluedragon.texturas.Importar tai_plate_us.dds _extraido_tai_plate_us.dds


