java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logoref_001_es.dds  _extraido_btlaf_logoref_001_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logoref_002_es.dds  _extraido_btlaf_logoref_002_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logoref_003_es.dds  _extraido_btlaf_logoref_003_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logo_blur_es.dds _extraido_btlaf_logo_blur_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logo_glow_es.dds _extraido_btlaf_logo_glow_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btlaf_logo_es.dds _extraido_btlaf_logo_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar btl_trance_es.dds _extraido_btl_trance_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_heada_es.dds _extraido_cmn_heada_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_hpmp_es.dds _extraido_cmn_hpmp_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_lay_main01_es.dds _extraido_cmn_lay_main01_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_lv_es.dds _extraido_cmn_lv_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_new_es.dds _extraido_cmn_new_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_next_es.dds _extraido_cmn_next_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar cmn_page_es.dds _extraido_cmn_page_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar gmov_logo_es.dds _extraido_gmov_logo_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar icon_status_02_es.dds _extraido_icon_status_02_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar icon_status_es.dds _extraido_icon_status_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar ic_itmeffect_es.dds _extraido_ic_itmeffect_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mgcg_hp_es.dds _extraido_mgcg_hp_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mgml_rank_es.dds _extraido_mgml_rank_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_critical_es.dds _extraido_mj_critical_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_defend_es.dds _extraido_mj_defend_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_guard_es.dds _extraido_mj_guard_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_miss_es.dds _extraido_mj_miss_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_quick_es.dds _extraido_mj_quick_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_reflection_es.dds _extraido_mj_reflection_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_shell_es.dds _extraido_mj_shell_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_shield_es.dds _extraido_mj_shield_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar mj_slow_es.dds _extraido_mj_slow_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar rst_cateun_es.dds _extraido_rst_cateun_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar rst_lvup_es.dds _extraido_rst_lvup_es.dds
java -cp ..\tools\tool bluedragon.texturas.Importar tai_plate_es.dds _extraido_tai_plate_es.dds


